name: Test SSH Connection


on:
  push:
    branches: [ main ]  # Change this to your main branch name if different
  workflow_dispatch:    # Allows manual workflow runs

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder'

      - name: Add remote host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Create test file
        run: |
          echo "This is a test file created by GitHub Actions on $(date)" > ssh_test.txt

      - name: Test SSH connection and file transfer
        run: |
          # First test simple SSH connection
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo SSH connection successful! && hostname && whoami"
          
          # Then test file transfer
          echo "Testing file transfer..."
          scp -o StrictHostKeyChecking=no -o BatchMode=yes ssh_test.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/services/ssh_test.txt
          
          # Verify file was created
          echo "Verifying file was created..."
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -la /root/services/ssh_test.txt && cat /root/services/ssh_test.txt"